repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-docstrings]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
    -   id: prettier
        types: [yaml, json, markdown, html, css, scss, javascript]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    -   id: markdownlint
        args: [--fix]

-   repo: local
    hooks:
    -   id: check-env
        name: Check .env file
        entry: bash -c '! grep -q "password\|secret\|key" .env || (echo "WARNING: Sensitive data found in .env file"; exit 1)'
        language: system
        files: \.env$
        pass_filenames: false

ci:
  autofix_commit_msg: "style: Auto-format with pre-commit hooks"
  autoupdate_commit_msg: "chore: Update pre-commit hooks"
